apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: remove-labels
  labels:
    app: nginx
  namespace: nginx
source: |-
  def mutate(resource):
      if "metadata" in resource and "labels" in resource["metadata"]:
          resource["metadata"]["labels"].pop("env", ' ')
          resource["metadata"]["labels"].pop("app1", ' ')
