apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
  namespace: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80 # Port the service is listening on.
      targetPort: 80 # Port the container is listening on.
  type: ClusterIP # Type of service (e.g., ClusterIP, NodePort, LoadBalancer).
